#
name: DOLIBARR_DEPLOY_TO_ACI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3
    - name: docker-check
      run:  echo ${{secrets.DOCKERCONTEXT}} > my-remote-server.dockercontext && docker context import dolibarr-docker-server my-remote-server.dockercontext
    - name: check1
      run: docker context use dolibarr-docker-server && docker ps

