#
name: DOLIBARR_DEPLOY_TO_ACI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: 'ssh://anil@20.84.92.143'
          context_name: 'dolibarr'
          ssh_cert: ${{ secrets.SSH_CERT }}
          ssh_key: ${{ secrets.SSH_KEY }}

      - run: docker context use dolibarr && docker ps


